.Dd $Mdocdate$
.Dt MENU 1
.Os
.Sh NAME
.Nm menu
.Nd interactive menus for the terminal
.\"
.Sh SYNPOSIS
.Nm menu
.Op Ar key=desc ...
.\"
.Sh DESCRIPTION
The
.Nm menu
utility creates an interactive menu in the terminal.
The menu items are read line by line from the standard input.

In the interactive interface, the user can select items using any
.Ar key
specified in the arguments to
.Nm menu .

When the user selects an item,
.Nm menu
exits and prints two lines on standard input:
.Bl -enum
.It
the key used to select the item,
.It
the selected item.
.El
.\"
.Sh EXAMPLES
Launch shell scripts from a directory:
.Bd -literal -offset 5n
ls *.sh | menu e=edit r=run | while read key && read item; do
	case $key in
		(e) $EDITOR "$item"
		(r) ./"$item"
	esac
done
.Ed

Create an interactive directory browser:
.Bd -literal -offset 5n
interactive_cd() {
	ls "$1" \\
	| menu return=cd space=browse backspace=up \\
	| while read key && read item; do
		case $key in
			(return) cd "$item"
			(space) interactive_cd "$item"
			(backspace) interactive_cd "$1"/..
		esac
	done
}
.Ed
.\"
.Sh KEY BINDINGS
.Bl -tag -width 10n
.It up, k
Go one line up
.It down, j
Go one line down
.It escape, h
Exit with error (return 1)
.El
.\"
.Sh AUTHORS
.Nm menu
is written by
.An John Ankarström ,
available {on the web|by e-mail} at john{.|@}ankarstrom.se.
